### ISSUE TITLE
DIscontinued

### ISSUE THREAD

**Issue by hejman** [witoza/Movie-Description-Plugin-for-Torrent#2]
Hi, this plugin is exactly what I am waiting for, has it been discontinued?

It does not seem to work at all for me

**Comment by witoza** [comment]
nope its very alive ;) Im updating it from time to time.  you want it for
the piratebay or kicass ?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-2322-b>
Virus-free
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-2322-b>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-06-15 19:47 GMT+05:30 hejman <notifications@github.com>:

> Hi, this plugin is exactly what I am waiting for, has it been discontinued?
>
> It does not seem to work at all for me
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/witoza/Movie-Description-Plugin-for-Torrent/issues/2>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABCGWmLlBBn7Hc7ABmeEqLrs1e8bX5AOks5qMAlfgaJpZM4I2Z5Z>
> .
>



-- 
Pozdrawiam / Best Regards
Witold Zegarowski

**Comment by hejman** [comment]
Hi thanks for the swift response!
I mostly use TPB, but kts is nice too, do you need any debugging information from me?

The plugin and developer mode is enabled, the icon is active in the browser but tpb did not change its appearance.

Thanks for working on this!

**Comment by witoza** [comment]
looks like I didn't make a commit after adding 'https://thepiratebay.org' to the mainfest.

just commited - please try again, download tarball and install and such..

Other thing is, since 2 days I'm on a travel in India (not sure how long :), and it looks like TPB is blocked here, so if you have any issues that will have to wait to be fixed until I return to my home country (or, you can fix that and push the changes) :|

cheers !

**Comment by hejman** [comment]
Hi, thanks the plugin now loaded properly.

However it does not work very well - see attachment (saved html in zip), thanks again for the nice work!

I dont know about india, but Danish block can be cercumvented by changing the DNS to ex. google (8.8.8.8).

Enjoy your travel!

**Comment by hejman** [comment]
HTML available here: http://pastebin.com/dMME7uVt

Sorry I cant attach to Github

**Comment by witoza** [comment]
Yeah, IMDB has changed its layout, damn,..., I knew that day would come eventually ;) Need to fix the code that extracts data from those pages. DNS change won't work. I will try some proxy but not today. I'll let you know once its fixed but as I said it may take some time.

**Comment by hejman** [comment]
Okay, too bad - thanks again for working on this!

I would love to be able to disinguish new an popular movies which has high imdb rating fast.
So much bad stuff around in the popular torrents!

Thanks!

**Comment by witoza** [comment]
Should be fixed. After reloading plugin, please go to Options and click 'clean cache'. 

Let me know if you have any issues or see possible improvements.

cheers

**Comment by hejman** [comment]
Hi, thanks it now works! Thank you so much this extension is incredible!

I noticed one movie did not resolve properly on IMDB:
https://thepiratebay.org/torrent/14954395/Footsoldier.2016.DVDRip.XViD-ETRG

It looked for "Footsoldier (2016)" on IMDB, but the real name on IMDB is:
Survival Instinct (2016) 
aka "Footsoldier"

Do you know if it possible to improve the lookup?

If this is too much work, nevermind as most movies resolve fine :-)

Thanks again!

**Comment by witoza** [comment]
I'm glad you like it :)

I did a quick fix so it does show 2 possibilites.

**Comment by hejman** [comment]
Thats awesome mate!

Would it be possible to add IMDB rating on the right side of the year to both when more than one matches has been found? - that would be great.

	
More than one match:

God of Foot Soldiers (2016)
Survival Instinct (2016)

I just had a look at infinite scroll, that's quite cool thanks!
- Are you planning on adding that the pirate bay anytime?

**Comment by hejman** [comment]
One more question - do you know of any way to not get this annoying "Disable developer mode" warning every time i open Google Chrome?

**Comment by witoza** [comment]
Hm.. I'll think about that but can't promise in the near future. Infinite scroll won't work for TPB as there is no similar structure "..../movies/moviePage" which I could use. 

Yeah, check the new description, basically uninstall the developer plugin as they do not overlap and install latest stable from google store.

-- cut here --
Download latest stable version from Google Store: https://chrome.google.com/webstore/detail/movie-description-plugin/paeiglbmkfigfilaemandggmmncoeoim
-- cut here --

**Comment by hejman** [comment]
Thanks man!
